# Generated by Django 4.1.1 on 2022-09-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('acc', models.CharField(max_length=5)),
                ('amt', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
