# Generated by Django 4.1.1 on 2022-09-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='date',
            field=models.CharField(default='00:00:00', max_length=50),
            preserve_default=False,
        ),
    ]
