# Generated by Django 4.1.1 on 2022-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_members_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='passw',
            field=models.CharField(default='12345', max_length=16),
            preserve_default=False,
        ),
    ]
